services:
  main:
    build: .
    container_name: your_bot
    network_mode: host
    restart: always
    volumes:
      - /home/exenifix/diary-data:/app/data
    environment:
      - DATABASE=diary
      - USER=diary
      - PASSWORD
      - TOKEN
